name: Toot

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 6,14,20 * * *'

jobs:
  toot:
    runs-on: ubuntu-latest
    env:
        MASTODON_INSTANCE: ${{secrets.MASTODON_INSTANCE}}
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get install -y gettext-base
        pip install requests
    - name: Toot
      run: |
        envsubst < config.json.example > config.json
        python toot.py
